title: Blog
default_lang: 'en '
author:
  name: 'Adrian Garcia Bloggs'
  email: adrian1994215@gmail.com
taxonomies:
  - category
  - tag
metadata:
  description: 'Materia Graficacion y animacion 6to Pucese'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
