title: GarciaBlog
default_lang: en
author:
  name: 'Adrian Garcia'
  email: adrian1994215@gmail.com
taxonomies:
  - category
  - tag
metadata:
  description: 'Estudio y Desarrollo practico de la materia Graficacion y Animacion'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
