enabled: true
top_level_version: false
github:
  position: top
  icon: 'Adrian Garcia'
default_taxonomy_category: docs
style: default
streams:
  schemes:
    theme:
      type: ReadOnlyStream
      prefixes:
        '': [user/themes/learn2-git-sync, user/themes/learn2]
enable_doc_versioning: false
hide_site_title: false
